spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/store?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 172.17.0.3